sudo: false
language: java
jdk:
    - oraclejdk8
node_js:
    - "8.12"

cache:
  directories:
  - "$HOME/.cache"

sudo: required
addons:
    chrome: stable

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
    - java -jar target/base-server-jar-with-dependencies.jar &
    - sleep 1
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - npm install

jobs:
  include:
    - script: "mvn test -B"
      name: "Maven test (BE)"
    - script: "node jasmine-checker.js"
      name: "FE and Net Test"
