
# @name login
POST http://localhost:8080/rest/user/login?remember=false http/1.1
User-Agent: rest-client
Content-Type: application/json

{
    "username": "Test",
    "password": "password"
}

###

# @name login
POST http://localhost:8080/rest/user/login?remember=false http/1.1
User-Agent: rest-client
Content-Type: application/json

{
    "username": "Admin",
    "password": "password"
}

###

GET http://localhost:8080/rest/user/all http/1.1
Cookie: {{login.response.headers.Set-Cookie}}
User-Agent: rest-client
Content-Type: application/json

PUT http://localhost:8080/rest/user/4 http/1.1
Cookie: {{login.response.headers.Set-Cookie}}
User-Agent: rest-client
Content-Type: application/json



