package se.lth.base.server.mail;

public enum EmailType {
    WELCOME,
    NEW_PASSENGER_REQUESTED,
    NEW_PASSENGER_ACCEPTED,
    BOOKING_CONFIRMED,
    RATING,
    FILTER_MATCH,
    PASSENGER_CANCELLED_TRIP,
    DRIVER_CANCELLED_DRIVE,
    WARNING,
    DRIVER_REMOVED_PASSENGER
}
